language: python

cache: pip

python:
  - "3.6"

addons:
  apt:
    packages:
      - make
      - gcc
      - realpath
      - verilator

script:
  - source scripts/set_env.sh
  - ./scripts/cgra_gen.sh

notifications:
  email:
    on_success: never
    on_failure: never
    on_error: never
