language: python

cache: pip

python:
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - gcc
      - realpath
      - verilator
      - csh
      - g++-7
      - gcc-7

install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99

script:
  - source scripts/set_env.sh
  - ./scripts/cgra_gen.sh
  - ./scripts/pnr_setup.sh
  - ./scripts/run_tests.sh

notifications:
  email:
    on_success: never
    on_failure: never
    on_error: never
